name: build and release

on: 
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Build with Gradle
        id: build
        run: ./gradlew clean build sourcesJar javadocJar  

      - uses: actions/upload-artifact@v4
        if: always() && (steps.build.outcome == 'failure')
        with:
          name: reports
          path: build/reports/tests/

      - name: Debug 1
        run: |
          ls -la build/libs

      - name: Decode
        if: ${{ always() && (steps.build.outcome == 'success') && github.ref == 'refs/heads/main'}}
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/sonatype_upload.gpg.b64
          base64 -d ~/.gradle/sonatype_upload.gpg.b64 > ~/.gradle/sonatype_upload.gpg

      - name: Release library  
        if: ${{ always() && (steps.build.outcome == 'success') && github.ref == 'refs/heads/main'}}
        run: |
          ./gradlew -s jreleaserRelease
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
